import { URL } from "url";

export function isValidUrl(urlString) {
  try {
    new URL(urlString);
    return true;
  } catch (e) {
    return false;
  }
}

export function contains_power_word(title) {
  const power_words = [
    "adoration",
    "passion",
    "exhilaration",
    "fulfillment",
    "euphoria",
    "bliss",
    "gratitude",
    "pleasure",
    "joy",
    "love",
    "excitement",
    "comfort",
    "delight",
    "warmth",
    "dread",
    "terror",
    "loathing",
    "misery",
    "torment",
    "despair",
    "distress",
    "unease",
    "rage",
    "sorrow",
    "fear",
    "anger",
    "frustration",
    "urgent",
    "limited",
    "exclusive",
    "last chance",
    "immediate",
    "fleeting",
    "now",
    "quickly",
    "deadline",
    "hurry",
    "scarce",
    "essential",
    "act fast",
    "instant",
    "only",
    "expert",
    "leading",
    "authoritative",
    "trusted",
    "credible",
    "renowned",
    "influential",
    "acclaimed",
    "prestigious",
    "certified",
    "top-rated",
    "reputable",
    "celebrated",
    "mysterious",
    "hidden",
    "secret",
    "unknown",
    "uncovered",
    "revealed",
    "astonishing",
    "intriguing",
    "unexpected",
    "sensational",
    "startling",
    "exclusive",
    "profound",
    "free",
    "bonus",
    "offer",
    "discount",
    "cheap",
    "save",
    "bargain",
    "best",
    "guaranteed",
    "premium",
    "special",
    "value",
    "cost-effective",
    "unbeatable",
    "freebie",
    "breakthrough",
    "easy",
    "fast",
    "effective",
    "efficient",
    "proven",
    "results",
    "innovative",
    "powerful",
    "transformative",
    "practical",
    "incredible",
    "revolutionary",
    "effortless",
    "achieve",
    "accomplish",
    "transform",
    "discover",
    "unlock",
    "master",
    "create",
    "build",
    "enhance",
    "develop",
    "lead",
    "conquer",
    "inspire",
    "innovate",
    "surpass",
    "VIP",
    "members-only",
    "exclusive",
    "insider",
    "privileged",
    "unique",
    "elite",
    "rare",
    "special",
    "select",
    "high-end",
    "tailored",
    "custom",
    "unparalleled",
    "limited-edition",
    "vibrant",
    "luxurious",
    "radiant",
    "crisp",
    "rich",
    "vivid",
    "stunning",
    "captivating",
    "exquisite",
    "bold",
    "sharp",
    "smooth",
    "enticing",
    "dazzling",
    "secure",
    "protected",
    "safe",
    "shielded",
    "guaranteed",
    "guarded",
    "reliable",
    "steadfast",
    "unwavering",
    "trustworthy",
    "stable",
    "unassailable",
    "simple",
    "easy",
    "clear",
    "straightforward",
    "intuitive",
    "user-friendly",
    "hassle-free",
    "effortless",
    "uncomplicated",
    "no-fuss",
    "basic",
  ];
  const title_words = title.toLowerCase().split(/\s+/); // Split by whitespace
  for (const word of power_words) {
    if (title_words.includes(word)) {
      return true;
    }
  }
  return false;
}

export function isKeywordMentioned(keyword, text) {
  return text.toLowerCase().includes(keyword.toLowerCase());
}
